name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=doc/ doc/deps.jl
      - name: Build and deploy site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=doc/ doc/build_site.jl
      - name: Build and deploy doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=doc/ doc/build_doc.jl
